#!/usr/bin/env bash

if [ ! -d ~/.emacs.d ]; then
  git clone https://github.com/plexus/chemacs2 ~/.emacs.d
elif [ ! -d ~/.emacs.d/.git ]; then
  rm -rf ~/.emacs.d
  git clone https://github.com/plexus/chemacs2 ~/.emacs.d
fi
[ ! -d ~/spacemacs ] && git clone https://github.com/syl20bnr/spacemacs ~/spacemacs
[ ! -f ~/.emacs-profiles.el ] && ln -s ~/oviramcs/emacs-profiles.el ~/.emacs-profiles.el
[ ! -f ~/oviramcs/spacemacs/custom.el ] && touch ~/oviramcs/spacemacs/custom.el
[ ! -f ~/oviramcs/vanilla/custom.el ] && touch ~/oviramcs/vanilla/custom.el
